Document: sidux-art-gfxbootsplash
Title: Debian sidux-art-gfxbootsplash Manual
Author: <insert document author here>
Abstract: This manual describes what sidux-art-gfxbootsplash is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/sidux-art-gfxbootsplash/sidux-art-gfxbootsplash.sgml.gz

Format: postscript
Files: /usr/share/doc/sidux-art-gfxbootsplash/sidux-art-gfxbootsplash.ps.gz

Format: text
Files: /usr/share/doc/sidux-art-gfxbootsplash/sidux-art-gfxbootsplash.text.gz

Format: HTML
Index: /usr/share/doc/sidux-art-gfxbootsplash/html/index.html
Files: /usr/share/doc/sidux-art-gfxbootsplash/html/*.html

  
